Repository Jing5s/Carrier_Web, pull requests merged in 2025-04, with the labels that each got.

#138 일기 주제 추천 api 연결
  src/features/diary/Chatbar/index.tsx
  src/features/diary/Chatbar/style.css.ts
  src/features/diary/Content/index.tsx
  src/features/diary/Content/style.css.ts
  src/features/diary/ReadContent/index.tsx
  src/features/diary/ReadContent/style.css.ts
  src/features/diary/services/diary.api.ts
  src/features/diary/services/diary.keys.ts
  src/features/diary/services/diary.query.ts
  src/pages/Diary/index.tsx
Labels: 📬 API, 🐞 BugFix, ✨ Feature

#150 main <- develop
  package.json
  pnpm-lock.yaml
  public/Vitamin Korean 4 Conversation.mp3
  src/app/routes.tsx
  src/entities/calendar/model.ts
  src/entities/calendar/type.ts
  src/features/Home/Calendar/CalendarModal/calendarModal.hook.ts
  src/features/Home/Calendar/Dropdown/index.tsx
  src/features/Home/Sidebar/MiniCalendar/index.tsx
  src/features/Home/services/home.api.ts
  src/features/Mail/CreateScheduleModal/index.tsx
  src/features/Proceed/Content/index.tsx
  src/features/Proceed/Content/style.css.ts
  src/features/Proceed/Visualizer/index.tsx
  src/features/Proceed/Visualizer/style.css.ts
  src/features/Proceed/hooks/useAudioRecorder.ts
  src/features/Proceed/service/proceed.api.ts
  src/features/Proceed/service/proceed.keys.ts
  src/features/Proceed/service/proceed.mutation.ts
  src/features/Proceed/service/proceed.query.ts
  src/features/Proceed/ui/BeforeIcon.tsx
  src/features/Proceed/ui/BigDownArrow.tsx
  src/features/Proceed/ui/NextIcon.tsx
  src/features/Proceed/ui/PauseIcon.tsx
  src/features/Proceed/ui/PlayIcon.tsx
  src/features/Proceed/ui/index.ts
  src/features/diary/hooks/useDiaryData.ts
  src/pages/Home/ui/Calendar/index.tsx
  src/pages/Home/ui/Calendar/style.css.ts
  src/pages/Proceed/index.tsx
  src/pages/Proceed/style.css.ts
  src/shared/components/DateTimePicker/index.tsx
  src/shared/lib/date/index.ts
  src/shared/lib/queryString/index.ts
  src/shared/types/global.d.ts
  src/widgets/NavigationBar/index.tsx
  src/widgets/NavigationBar/style.css.ts
  src/widgets/NavigationBar/ui/Proceed.tsx
Labels: 🌏 Deploy

#164 녹음관련 QA 수정 Hotfix/#163
  pnpm-lock.yaml
  src/features/Proceed/Content/index.tsx
  src/features/Proceed/Content/style.css.ts
Labels: 🐞 BugFix
